;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "kitchen-sink-skill")
(def path ".")
(def version "0.1.78")
(def tag "0.1.78")
(def generated-at "2020-05-18T23:53:53Z")
