;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "kitchen-sink-skill")
(def path ".")
(def version "0.1.76")
(def tag "v0.1.76")
(def generated-at "2020-05-15T17:19:17Z")
